import { avaiableColors } from './../avaiable-colors';
import { GenderType, LAYER_ID } from './../../interface/avatar.interface';
import { LayerItemConfig } from './../../interface/layer.interface';
const bangsConfig: LayerItemConfig[] = [
  {
    filename: '头像初稿_男发-9',
    genderType: GenderType.MALE,
    avaiableColorGroups: avaiableColors[LAYER_ID.BANGS],
    colorNotSameAs: [LAYER_ID.BACKGROUND],
    weight: 10,
    removeLayers: [LAYER_ID.HAIR],
  },
  {
    filename: '头像初稿_男发-11',
    genderType: GenderType.MALE,
    avaiableColorGroups: avaiableColors[LAYER_ID.BANGS],
    colorNotSameAs: [LAYER_ID.BACKGROUND],
    weight: 10,
    removeLayers: [LAYER_ID.HAIR],
  },
  {
    filename: '头像初稿_男发-13',
    genderType: GenderType.MALE,
    avaiableColorGroups: avaiableColors[LAYER_ID.BANGS],
    colorNotSameAs: [LAYER_ID.BACKGROUND],
    weight: 10,
    removeLayers: [LAYER_ID.HAIR],
  },
  {
    filename: '头像初稿_男发-14',
    genderType: GenderType.MALE,
    avaiableColorGroups: avaiableColors[LAYER_ID.BANGS],
    colorNotSameAs: [LAYER_ID.BACKGROUND],
    weight: 10,
    removeLayers: [LAYER_ID.HAIR],
  },
  {
    filename: '头像初稿_男发-15',
    genderType: GenderType.MALE,
    avaiableColorGroups: avaiableColors[LAYER_ID.BANGS],
    colorNotSameAs: [LAYER_ID.BACKGROUND],
    weight: 10,
    removeLayers: [LAYER_ID.HAIR],
  },
  {
    filename: '头像初稿_男发-20',
    genderType: GenderType.MALE,
    avaiableColorGroups: avaiableColors[LAYER_ID.BANGS],
    colorNotSameAs: [LAYER_ID.BACKGROUND],
    weight: 10,
    removeLayers: [LAYER_ID.HAIR],
  },
  {
    filename: '头像初稿_女刘海-24',
    colorSameAs: LAYER_ID.HAIR,
    genderType: GenderType.FEMALE,
    avaiableColorGroups: avaiableColors[LAYER_ID.BANGS],
    colorNotSameAs: [LAYER_ID.BACKGROUND],
    weight: 10,
    removeLayers: [LAYER_ID.FACIAL_HAIR],
  },
  {
    filename: '头像初稿_女无刘海-22',
    colorSameAs: LAYER_ID.HAIR,
    genderType: GenderType.FEMALE,
    avaiableColorGroups: avaiableColors[LAYER_ID.BANGS],
    colorNotSameAs: [LAYER_ID.BACKGROUND],
    weight: 10,
    removeLayers: [LAYER_ID.FACIAL_HAIR],
  },
  {
    filename: '头像初稿_女无刘海-23',
    colorSameAs: LAYER_ID.HAIR,
    genderType: GenderType.FEMALE,
    avaiableColorGroups: avaiableColors[LAYER_ID.BANGS],
    colorNotSameAs: [LAYER_ID.BACKGROUND],
    weight: 10,
    removeLayers: [LAYER_ID.FACIAL_HAIR],
  },
  {
    filename: '头像初稿_女刘海-21',
    colorSameAs: LAYER_ID.HAIR,
    genderType: GenderType.FEMALE,
    avaiableColorGroups: avaiableColors[LAYER_ID.BANGS],
    colorNotSameAs: [LAYER_ID.BACKGROUND],
    weight: 10,
    removeLayers: [LAYER_ID.FACIAL_HAIR],
  },
  // {
  //   filename: '头像初稿_女刘海-21',
  //   genderType: GenderType.UNSET,
  //   avaiableColorGroups: avaiableColors[LAYER_ID.HAIR],
  //   colorNotSameAs: [LAYER_ID.BACKGROUND],
  //   weight: 1,
  // },
];
export default bangsConfig;
